version: '3'
services: 
  client: 
    container_name: client 
    build: ./client
    image: oakel/plej-client
  server: 
    container_name: server
    restart: always
    build: ./server
    image: oakel/plej-server
    environment: 
      - NODE_ENV=production
      - PORT=3000
    ports: 
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - client
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"