version: '3'
services: 
  server: 
    container_name: server
    restart: always
    build: ./server
    image: oakel/plej-server
    environment: 
      - NODE_ENV=production
      - PORT=80
    ports: 
      - "80:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"